### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by phdosilva** [phdosilva/AnkiAutomation#1]
- [x] Incriese on pronounce: get pronunciation with '(' and ')'.
- [x] get audio from wordreference.
- [ ] frasal verbs search bug fix
